on: push
name: Build ChopChop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Unit Tests
      uses: go test ./...
    - name: Install gox
      run: go get github.com/mitchellh/gox
    - name: Build using gox
      run: gox -ldflags "-X main.Version=$BUILD_VERSION -X main.BuildDate=$BUILD_DATE" -output "dist/ChopChop_{{.OS}}_{{.Arch}}"
    - name: Upload ChopChop builds
      uses: actions/upload-artifact@v2
      with:
        name: chopchop-artifacts
        path: dist/*
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: gz
        GHR_PATH: dist/
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}